# Generated by Django 3.0.7 on 2020-07-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_id', models.IntegerField()),
                ('category', models.CharField(max_length=10)),
                ('cuisine', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('system_stock', models.IntegerField()),
                ('actual_stock', models.IntegerField(default=0)),
                ('meals', models.ManyToManyField(to='inventory.Meal')),
            ],
        ),
    ]
