# Generated by Django 3.0.7 on 2020-07-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='meals',
            field=models.ManyToManyField(blank=True, related_name='items', to='inventory.Meal'),
        ),
    ]
